# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FcgDataBase
    ports:
      - "5432:5432"
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres -d FcgDataBase"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
  api:
    build:
      context: .
      dockerfile: FCG.API/Dockerfile
    container_name: FcgApi
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db; Database=FcgDataBase; Username=postgres; Password=postgres"
    ports: 
      - "8080:8080"  
    depends_on:
      db:
        condition: service_healthy 
networks:
  default:
    name: fcg-api
    driver: bridge      
      